name: ras2fim
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - curl=7.71.1
  - cycler=0.10.0
  - expat=2.4.1
  - fiona=1.8.13.post1
  - fonttools=4.25.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.6.0
  - h5netcdf=0.11.0
  - h5py=3.2.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2019.0.0
  - intel-openmp=2021.3.0
  - joblib=1.0.1
  - jpeg=9b
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - libcurl=7.71.1
  - libgdal=3.0.2
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.4.3
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - networkx=2.6.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - pandas=1.3.1
  - pillow=8.3.1
  - pip=21.2.2
  - postgresql=12.2
  - proj=6.2.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyreadline=2.1
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pywin32=227
  - rasterio=1.1.1
  - rioxarray=0.6.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - shapely=1.7.1
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tiledb=2.2.9
  - tk=8.6.10
  - tornado=6.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
